server:
  port: 1219
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyyMMddHHmmss
    time-zone: GMT+8
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#pagehelper分页插件配置
web.webupload: /webupload

# 日志配置
logging:
  level:
    org:
      mybatis: info
    com:
      zzq: debug
  file: pkusoft.log

mybatis:
  datasource:
    config[0]:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://23.95.189.109:5566/zhangzq?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull
      username: root
      password: pkus0ftadm1n
      mapper-scanner: tk.mybatis.spring.mapper.MapperScannerConfigurer
      base-package: com.zzq.usercenter
    config[1]:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://23.95.189.109:5566/licm?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull
      username: root
      password: pkus0ftadm1n
      mapper-scanner: tk.mybatis.spring.mapper.MapperScannerConfigurer
      base-package: com.zzq.licm
    config[2]:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://23.95.189.109:5566/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull
      username: root
      password: pkus0ftadm1n
      mapper-scanner: tk.mybatis.spring.mapper.MapperScannerConfigurer
      base-package: com.zzq.zhangzq
